### ISSUE TITLE
Ein alter freund 

### ISSUE THREAD

**Issue by KeBieee** [Tr0llagent/Tr0llagent#1]
Hey, trolli ich bin es Kebiee hast du Bock vielleicht demnächst mal wieder auf dc zu quatschen sorry das ich dich über diesen weg erreiche ich hab nichts anderes gefunden, womit ich dich erreichen könnte irgendwie ist der Kontakt zwischen uns Flöten gegangen :(

**Comment by Tr0llagent** [comment]
Sorry hab's erst jetzt gesehen
Add mich einfach Trollagent#4078
